### ISSUE TITLE
Constructor with array not working with Typescript

### ISSUE THREAD

**Issue by milbrandt** [PgBiel/ztimespan#1]
Typescript 3.7.2
ztimespan 2.1.0

In the `Readme.md` the Sting-ified example is not working:

    import {Time} from 'ztimespan'
    var myOtherTimeSpan = new Time(["y", 4, "m", 7]);

Error message:
>TS2345: Argument of type '["y", number, "m", number]' is not assignable to parameter of type 'number | Time | Date | [TimeUnit, number] | undefined'.
  Type '["y", number, "m", number]' is not assignable to type '[TimeUnit, number]'.
    Types of property 'length' are incompatible.
      Type '4' is not assignable to type '2'.

**Comment by PgBiel** [comment]
I'll take a look

**Comment by PgBiel** [comment]
Fixed on version 2.1.1 (sorry for the delay) 👍
